apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME-deployment
  namespace: $APP_NAMESPACE
  labels:
    app: $APP_NAME
spec:
  replicas: 3
  selector:
    matchLabels:
      app: $APP_NAME
  template:
    metadata:
      labels:
        app: $APP_NAME
    spec:
      containers:
      - name: $APP_NAME
        image: $IMAGE_REPO:$IMAGE_NAME
        resources:
          requests:
            memory: '64Mi'
            cpu: '250m'
          limits:
            memory: '128Mi'
            cpu: '500m'
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
         - name: DB_USER
           valueFrom:
             secretKeyRef:
               name: db-secret
               key: db_user
         - name: DB_PWD
           valueFrom:
             secretKeyRef:
               name: db-secret
               key: db_pwd
         - name: DB_NAME
           valueFrom:
             secretKeyRef:
               name: db-secret
               key: db_name
         - name: DB_SERVER
           valueFrom:
             configMapKeyRef:
              name: db-config
              key: db_server
---
apiVersion: v1
kind: Service
metadata:
  name: $APP_NAME-service
  namespace: $APP_NAMESPACE
spec:
  selector:
    app: $APP_NAME
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
