pipeline {
    agent any
    tools {
        nodejs "node"
    }

    stages {
        stage('Tests') {
            steps {
                script {
                    dir('app') {
                        withNPM(npmrcConfig: 'null') {
                            sh "npm i"
                            sh "npm run test"
                        }
                    }
                }
            }
        }
    }
}