pipeline {
    agent any
    tools {
        nodejs "node"
    }

    stages {
        stage('Tests') {
            steps {
                script {
                    dir('Ex7 - Automation & CICD/app') {
                            sh "npm i"
                            sh "npm run test"
                    }
                }
            }
        }
    }
}